### ISSUE TITLE
Warning: method redefined; discarding old initialize

### ISSUE THREAD

**Issue by sergey-chechaev** [tram-rb/tram-policy#3]
What the best solution call validation methods in Tram::Policy with interface Dry::Initializer without warnings?

I call validation in constructor and have warning:

```
warning: method redefined; discarding old initialize
rvm/gems/ruby-2.3.0/gems/dry-initializer-1.4.0/lib/dry/initializer/dsl.rb:35: warning: previous definition of initialize was here
```

Example code

```
module Tram
  class Policy
    extend Dry::Initializer

    def initialize(*args)
      super(*args)
      validation_methods = self.class.instance_eval { @validation_methods }

      return unless validation_methods
      validation_methods.each do |method|
        send(method)
      end
    end
  # ...
```

**Comment by nepalez** [comment]
Hmm... that's strange, thank you!

I'll look at this issue in context of dry-initializer

btw: I think you'd better use class-level attribute for the list of validation methods for not invoking slow `instance_eval` at runtime without necessity:

```ruby
self.class.validation_methods
```

There is no problem with additional class method here because policy objects has very narrow responsibility, and you needn't worrying about possible conflicts.

**Comment by nepalez** [comment]
Another thing -- you don't need `super(*args)`, just use `super` ;)

**Comment by nepalez** [comment]
Hah! That's it https://github.com/dry-rb/dry-initializer/issues/29

**Comment by sergey-chechaev** [comment]
👍
